name: "Microsoft Teams Releases Bot"
description: "Bot to notify softaware releases to Microsoft Teams"
author: "Albert Álvarez Carulla"

inputs:
  webhook:
    description: "Webhook URL of the MS Teams channel."
    required: true
  tag-or-release:
    description: 'Indicates if the is a release or tag notification. Options: tag, release.'
    required: true
    default: "tag"
  release-notes:
    description: "Release notes for the version."
    required: false
    default: "No release notes provided."
  version:
    description: "Version of the release."
    required: true
  environment:
    description: "Environment where the release is being deployed. Options: development, production."
    required: true
  action-url:
    description: "URL to the version that triggered the release."
    required: true
  application-name:
    description: "Name of the application being released."
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
